travis:
  secure:
    BINSTAR_TOKEN: gI1I/h5ewGks0gj6i29CVJhmicq3r6hfuWD2+676gJj2EA9ZWQe9CjAmQ2+Je7n45E1hEIJsgMtzqhPH0+nlu9YoKszmOeNZfdOWiNFqIV+ah3W8k9bjPq/zudkewlpBZvAzDPSQZW3zoZ6OBJ7xAUe+p26FxjVqizbTgPyI3n0exPATJk+mb/zI2eukUiEdkf3Y+tJ4oEMdMoySq/ErN4MOMin057G3NQ2uxn8WvfqaJE8q8Y0oLiq8RlM8TrFu7p0YEa6MtpXmK24BQGemryCHLxgZDKuci59BmgN7ZE+LbXl2qd+C/5tuBwQqE6KjGaWdK3n1wr2l3eQfc73el3gEws2G5mC2Ognk0MOEjauFjeouu56akbFWUOge1s3r83XttyWmbVxLQdiEQxTzMIHeBD+JM6cterUcw62epmFeFMrF8Jk5wtJ75VBjneXHt3RdAzsrON0oe3IYdTmbLMqs1YaGz8SfmkdRSgrZfKLsnJLUm/cSQKNcF+2qa/294UtAZp0WgAirrmYUjg1J/F+jmI22ya23PRA9Uum0kh5nwrV4R0O4EvK2e5+2HJiGZ+auvLyJy9rUmBJvNEARbJgkUvVU3cz2ZUmdqtreD2HhQN9L3UWlVUQPVCOI+Yd8+5R4OoMViADAQkTLQWfzcRPA5am5bflHFIWtZlAXZVM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
